### ISSUE TITLE
Can't get app-portage/emlop zsh completions working

### ISSUE THREAD

**Issue by xfzv** [vincentdephily/moltonel-ebuilds#2]
I'm having some issues with `app-portage/emlop` zsh completions.

`# USE="zsh-completion" emerge app-portage/emlop`

https://github.com/vincentdephily/moltonel-ebuilds/blob/f18eb98be6d5495639c12969778578c299d1ae45/app-portage/emlop/emlop-0.4.1.ebuild#L98-L102

This part of the ebuild does create `/usr/share/zsh/site-functions/_emlop` but the file is empty.

`% ls -l /usr/share/zsh/site-functions/_emlop`:

```
.rw-r--r-- 0 root root   /usr/share/zsh/site-functions/_emlop
```

`% emlop complete zsh > _emlop && sudo mv _emlop /usr/share/zsh/site-functions/_emlop && sudo chown root:root /usr/share/zsh/site-functions/_emlop` solves the empty file issue:

```
rw-r--r-- 5,6k root root  /usr/share/zsh/site-functions/_emlop
```

but completions are still not working.

If I manually source `_emlop` in my `.zshrc` with `source /usr/share/zsh/site-functions/_emlop`, I'm getting `_emlop:12: command not found: _arguments` every time I open a new shell and completions are not working either.

If I run `% source /usr/share/zsh/site-functions/_emlop`, I'm getting `_arguments:comparguments:325: can only be called from completion function`. Still no completions with that method.

I'm probably missing something. `qlop` completions work fine for instance.

![qlop_zsh_completions](https://user-images.githubusercontent.com/78810647/129920573-b607aee2-bc69-4c7d-ac72-8213893790a8.png)

Any idea?

Thanks!

**Comment by vincentdephily** [comment]
Thanks for the bug report.

# Empty completion file

It looks like the ebuild was using the already-installed `emlop` to generate completions, which will fail on first install.

I've pushed a fixed ebuild, please test it, making sure to uninstall emlop fist: `emerge --sync && emerge -C emlop && emerge emlop`.


#  `_argument` errors

Completion works for me. Did you restart your shell after fixing the completion file ?

It seems those files can't simply be `source`d, there's a special way to load them. I'm not a regular zsh user but I have this in my `~/.zshrc` (can't remember whether I needed manual steps to get there)

```
# The following lines were added by compinstall
zstyle :compinstall filename '/home/work/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
```

But whatever you have on your side, if other completions work then emlop completion should work too. Please try with a fresh shell.

**Comment by xfzv** [comment]
Can confirm that https://github.com/vincentdephily/moltonel-ebuilds/commit/df3c1e663973478a5c1fd73f378ecd4a54434cf6 solved the empty `/usr/share/zsh/site-functions/_emlop` issue

And zsh completions work just fine now, not sure why.

![image](https://user-images.githubusercontent.com/78810647/130112394-23aa578d-bc0c-4b74-b1e4-2bd4775b4141.png)
![image](https://user-images.githubusercontent.com/78810647/130112424-dec3716b-32f3-4f28-b793-050212366258.png)

Thank you!
